test_demo/urls.py
from app01 import views
from app02 import views as app02_views
from app02.models import Department, Employee, PrettyNum
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff', 'password']

# ViewSets define the view behavior.


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


class EmployeeSerializer(serializers.ModelSerializer):
    class Meta:
        model = Employee
        fields = ['url', 'name', 'age', 'account',
                  'password', 'hiredate', 'gender', 'depart']


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer


class DepartmentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Department
        fields = ['url', 'title', 'add_date', 'mod_date']


class DepartmentViewSet(viewsets.ModelViewSet):
    queryset = Department.objects.all()
    serializer_class = DepartmentSerializer


class PrettyNumSerializer(serializers.ModelSerializer):
    class Meta:
        model = PrettyNum
        fields = ['url', 'mobile', 'price', 'level', 'status']


class PrettyNumViewSet(viewsets.ModelViewSet):
    queryset = PrettyNum.objects.all()
    serializer_class = PrettyNumSerializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'employee', EmployeeViewSet)
router.register(r'department', DepartmentViewSet)
router.register(r'pretty_num', PrettyNumViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    # DRF
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    # path('', RedirectView.as_view(url='employee/list')),
    path('home/', views.home_index),
    path('home/templates', views.home_templates),
    path('grammar/summary', views.grammar_summary),

    # 登录案例
    path('user/add', views.user_add),
    path('user/list', views.user_list),
    path('user/login', views.user_login),
    path('user/delete', views.user_delete),


    # FBV 模式
    path('dept/list', app02_views.dept_index),
    path('employee/list', app02_views.employee_index),
    path('employee/add', app02_views.employee_add_user_form),
    path('employee/<int:nid>/edit', app02_views.employee_edit_user),
    path('employee/<int:nid>/delete', app02_views.employee_delete_user),


    # CBV 模式 - mobile
    path('mobile/list', app02_views.Mobile.as_view()),
    path('mobile/<int:nid>', app02_views.mobile_list),
    # path('mobile/<int:nid>', app02_views.mobile_form_prompt),

    # API
    path('api/dept', app02_views.dept),
    path('api/employee/add_user', app02_views.employee_add_user)
]

app02/models.py
from django.db import models
from datetime import date


# Create your models here.
import django.utils.timezone as timezone
class Department(models.Model):
    today = date.today()
    title = models.CharField(verbose_name='标题', max_length=20)
    add_date = models.DateTimeField(verbose_name='创建时间', default=timezone.now, db_comment='部门创建时间')
    mod_date = models.DateTimeField(verbose_name='创建时间', auto_now=True, db_comment='部门修改时间')

    def __str__(self) -> str:
        return self.title


class Employee(models.Model):
    name = models.CharField(verbose_name='员工名称', max_length=20)
    age = models.IntegerField(verbose_name='员工年龄')
    account = models.CharField(verbose_name='员工账号', max_length=20)
    password = models.CharField(verbose_name='员工密码', max_length=20)
    hiredate = models.DateTimeField(verbose_name='入职时间')

    # 联表加约束条件
    '''
    联表约束
        1. 关联部门的在插入数据时检验是否存在
        2. 当部门表删除数据时，员工表有所关联的数据将“联级删除”
    '''
    # depart = models.ForeignKey(to=Department, to_field=)
    depart = models.ForeignKey(verbose_name='部门' ,to=Department, to_field='id', on_delete=models.CASCADE)
    # 置空处理
    # depart = models.ForeignKey(to='Department', to_field='id', null=True, blank=True, on_delete=models.SET_NULL)

    # 性别约束
    gender_choices = (
        (1,'男'),
        (2,'女')
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)


class PrettyNum(models.Model):
    mobile = models.CharField(verbose_name='手机号码', max_length=11)
    price = models.IntegerField(verbose_name='价格', default=0)

    level_choices = (
        (1, '一级'),
        (2, '二级'),
        (3, '三级'),
        (4, '四级'),
        (5, '五级'),
    )

    level = models.SmallIntegerField(verbose_name='手机等级', choices=level_choices, default=1)

    status_choices = (
        (1, '未启用'),
        (2, '已使用')
    )
    status = models.SmallIntegerField(verbose_name='手机号使用状态', choices=status_choices, default=1)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_created=True, default=timezone.now)

app02/views.py
import json
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse, QueryDict
from django.forms import ModelForm
from django import forms
from django.views import View
from app02.models import Department, Employee, PrettyNum


# Create your views here.
def dept_index(request):
    dept_list = Department.objects.all()
    print(dept_list)
    return render(request, 'list.html', {"dept_list": dept_list})


def employee_index(request):
    list = Employee.objects.all()
    context = {
        'depart_list': Department.objects.all(),
        'gender_choices': Employee.gender_choices
    }
    # for obj in list:
    #     print('转换数据库数据 --> ', obj.get_gender_display(), obj.hiredate.strftime('%Y-%m-%d'))
    #     print('联表查询部门表 --> ', obj.depart.title)
    return render(request, 'employees.html', {'employees': list, 'context' :context})


class EmployeeForm(ModelForm):
    # 需要独立编写校验规则
    name = forms.CharField(min_length=2,label='员工姓名')
    password = forms.CharField(min_length=6,label='员工密码')
    hiredate_attrs = {'placeholder': "yyyy-MM-dd",'class': 'layui-input','lay-verify':'date','id':'date','autocomplete':'off'}
    hiredate = forms.DateTimeField(label='入职时间',widget=forms.TextInput(attrs=hiredate_attrs))
    class Meta:
        model = Employee
        fields = ['name', 'password', 'gender', 'age', 'account', 'hiredate','depart']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
          # 通过插件添加 input 属性
          if name == 'hiredate':
              continue
          field.widget.attrs = {"class": 'layui-input', "lay-verify": "required", "placeholder": "请输入{}".format(field.label),'autocomplete':'off'}


def employee_add_user_form(request):
    if request.method == 'GET':
      form = EmployeeForm()
      return render(request, 'employees_add.html', { 'form': form})
    if request.method == 'POST':
        form = EmployeeForm(data=request.POST)
        if form.is_valid():
            form.save()
        else:
            return render(request, 'employees_add.html', { 'form': form})
    return redirect('/employee/list')


def employee_add_user(request):
    if(request.method == 'POST'):
      data = json.loads(request.body)
      Employee.objects.create(**data)
    res_data = {"code": 200, "data": data, "msg": "保存成功"}
    return JsonResponse(res_data)


def employee_edit_user(request, nid):
    row_object = Employee.objects.filter(id=nid).first()
    if request.method == 'GET':
      form = EmployeeForm(instance=row_object)
      return render(request,'employees_edit.html', { 'form':form})

    form = EmployeeForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return render(request, 'employees_edit.html', { 'form': form})
    else:
        return render(request, 'employees_edit.html', { 'form': form})


def employee_delete_user(request, nid):
    row_object = Employee.objects.filter(id=nid).first()
    if request.method == 'DELETE' and row_object:
        row_object.delete()
        return HttpResponse('删除员工成功')


def dept(request):
    nid = request.params.get('id')
    dept_name = request.params.get('deptName')

    if request.method == 'POST':
        Department.objects.create(title=dept_name)

    if request.method == 'PUT':
        Department.objects.filter(id=nid).update(title=dept_name)

    if request.method == 'DELETE':
        Department.objects.filter(id=nid).delete()

    res_data = {"code": 200, "data": dept_name, "msg": "请求成功"}
    return JsonResponse(res_data)


class PrettyNumForm(ModelForm):
    # 需要独立编写校验规则
    mobile = forms.IntegerField(min_value=11,label='手机号码')
    class Meta:
        model = PrettyNum
        fields = ['mobile', 'price', 'level','status',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
          # # 通过插件添加 input 属性
          # if name == 'hiredate':
          #     continue
          field.widget.attrs = {"class": 'layui-input', "lay-verify": "required", "placeholder": "请输入{}".format(field.label),'autocomplete':'off'}

from django.core.serializers import serialize
class Mobile(View):
    def get(self, request):
        list = PrettyNum.objects.all()
        form = PrettyNumForm()
        return render(request, 'mobile/list.html', { 'mobile_list' : list, 'form': form})

    def post(self, request):
        data = json.loads(request.body)
        PrettyNum.objects.create(**data)
        return HttpResponse(request)

    def delete(self, request):
        data = json.loads(request.body)
        id = data.get('id')
        row_arr = PrettyNum.objects.filter(id=id)
        array = serialize("json",row_arr)

        row_arr.delete()
        return JsonResponse({'data': json.loads(array)})



def mobile_form_prompt(request, nid):
    row_object = PrettyNum.objects.filter(id=nid).first()
    form = PrettyNumForm(instance=row_object)
    return render(request, 'common/form_prompt.html', { 'form': form })


def mobile_list(request, nid):
    if request.method == 'GET':
      row_object = PrettyNum.objects.filter(id=nid)
      json_data = serialize("json", row_object)
      return JsonResponse(json.loads(json_data)[0]['fields'])

    if request.method == 'UPDATE':
        print(request.method)
        data = json.loads(request.body)
        PrettyNum.objects.filter(id=nid).update(**data)
        return HttpResponse('hi')

app02/templates/mobile/add_mobile.html
  <div class="layui-card-body">
    <form id="add_mobile"
          name='addEmployess'
          class="layui-form layui-form-pane"
          action=""
          style="display: none;
                 padding: 16px">

      {% for item in form %}
      <div class="layui-form-item">
        <label class="layui-form-label">{{ item.label }}</label>
        <div class="layui-input-inline">
          {{ item }}
        </div>
        <div class="layui-form-mid layui-text-em layui-font-red">{{ item.errors.0 }}</div>
      </div>
      {% endfor %}
      <div class="layui-form-item">
        <button class="layui-btn" lay-submit lay-filter="addMobile">确认</button>
        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
      </div>
    </form>
  </div>

app02/templates/mobile/list.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
  <div class="layui-card-header">
    <h2>靓号管理</h2>
  </div>
  <div class="layui-card-body">
    <button type="button"
            class="layui-btn layui-bg-primary"
            lay-on="mobileFunc">添加手机号码</button>
    <table class="layui-table" style="text-align: center;">
      <colgroup>
        <col width="80">
        <col width="120">
        <col width="200">
        <col width="120">
      </colgroup>
      <thead>
        <tr>
          <th>ID</th>
          <th>手机号码</th>
          <th>价格</th>
          <th>号码等级</th>
          <th>号码状态</th>
          <th>创建时间</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        {% for item in mobile_list %}
          <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.mobile }}</td>
            <td>{{ item.price }}元</td>
            <td>{{ item.get_level_display }}</td>
            <td>{{ item.get_status_display }}</td>
            <td>{{ item.create_date|date:'Y-m-d h:i:s'  }}</td>
            <td>
              <button type="button"
                      class="layui-btn layui-bg-blue"
                      lay-on="mobileFunc"
                      dispatch="update"
                      data-id="{{ item.id }}">修改</button>
              <button type="button"
                      class="layui-btn layui-bg-red"
                      lay-on="mobileFunc"
                      dispatch="delete"
                      data-id="{{ item.id }}">删除</button>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% include './prompt_form.html' %}

{% endblock %}
{% block js %}
  <script src="{% static 'js/prettyNum.js' %}"></script>
{% endblock %}

app02/templates/mobile/prompt_form.html
  <div class="layui-card-body">
    <form id="formData"
          class="layui-form layui-form-pane"
          action=""
          style="display: none;
                 padding: 16px">

      {% for item in form %}
      <div class="layui-form-item">
        <label class="layui-form-label">{{ item.label }}</label>
        <div class="layui-input-inline">
          {{ item }}
        </div>
        <div class="layui-form-mid layui-text-em layui-font-red">{{ item.errors.0 }}</div>
      </div>
      {% endfor %}
      <div class="layui-form-item">
        <button class="layui-btn" lay-submit lay-filter="update">保存</button>
        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
      </div>
    </form>
  </div>